# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
tone_instructions: "Please act as we were in Tolkien's Middle-earth. Write in the style of J.R.R. Tolkien."
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords: []
    drafts: false
chat:
  auto_reply: true
