#!/bin/sh

#
#  postinstall
#  Bootstrap Buddy
#
#  Copyright 2024 Inetum
#
#  Based on Escrow Buddy
#  Copyright 2023 Netflix
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

#  This is the postinstall script executed during Bootstrap Buddy's installation.
echo "Adding Bootstrap Buddy to authorization database..."
"$3/Library/Security/SecurityAgentPlugins/Bootstrap Buddy.bundle/Contents/Resources/AuthDBSetup.sh"
