name: "Pre-Commit"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: pre_commit_${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/mise

      - run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
          pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage=manual
